server:
  port: 8082

spring:
  application:
    name: project-service

  datasource:
    url: jdbc:postgresql://localhost:5434/project_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET:#@!#assaD!@@#!@$SAD@$!%@!%@Ss$#!@$@$FASFQ@QFSAFASF_CHANGE_ME}

services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
    app-id: ${USER_SERVICE_APP_ID:user-service}
  task-service:
    url: ${TASK_SERVICE_URL:http://localhost:8083}
    app-id: ${TASK_SERVICE_APP_ID:task-service}
